### ISSUE TITLE
Enrolment upon approval Plugin for Moddle doesnt work in Moodle 3.6

### ISSUE THREAD

**Issue by deepzzrs** [catalyst/moodle-enrol_auto#20]
The issue is the latest version of the Plugin doesnt work well with Moodle 3.6 which is my production site.I am aware of the fact that the latest plugin released is for Moodle 3.5 and there are no description of support for Moodle 3.6.

If this problem persists for everyone then May I know the approximate Date of release for Moodle 3.6 ?
else let me know and I will let you know a detailed report of the problem which i facce when I use it in Moodle 3.6.

Problem : Table preferences which lists the users enrolled doesnt show up.

Regards,
Deepak RS

**Comment by bynare** [comment]
Sorry @deepzzrs, unless you can provide me with steps to reproduce your issue, I won't be able to help out here...

**Comment by skeetermedia** [comment]
I have just installed this on ver 3.6.3, added a method to a course, set it to autoenrol on enter course.
I have tried numerous times as a user to enrol in the course and it doesn't seem to work.
the user can view the course but are not enrolled so their progress is not tracked.
what am I doing wrong?

**Comment by danmarsden** [comment]
we don't really support this plugin on Moodle anymore - there are other plugins better suited for this within the moodle.org plugins db (we only really support the uses of this plugin in Totara sites these days.)
