### ISSUE TITLE
Block Course Participant Re-Auto Enrollment 

### ISSUE THREAD

**Issue by nayabbukhari** [catalyst/moodle-enrol_auto#28]
Issue: Plugin auto-enrol Enrol course participant again with auto enrol method. 

Steps:
A   Admin: Create a new student (Manual Authentication) Tested
B.  Admin: Enable auto/enrol  plugin
C.  Admin: Create a test Course
D   Admin: Add auto-enrol instance enrollment method in the course 
E   Admin: Assign student course using "manual enrol method". 
F   Student: Login as student & access the course
G  Admin: View course participate
Result: There will be two enrolment method (Manual & Auto).  
Solution: [block-course-participant-auto-enrolment.patch](https://drive.google.com/file/d/1zIropH7zGe6VKb45hVvBif1TMhEGkOet/view?usp=sharing)

**Comment by danmarsden** [comment]
this is expected behaviour. Closing.
