### ISSUE TITLE
Auto Enrol on activity trigger needs guest access? 

### ISSUE THREAD

**Issue by VOOM108** [catalyst/moodle-enrol_auto#34]
When setting a course to auto enrol with activity access as trigger, it asks for guest access needed to work. Guest access without key would make the plugin useless, with key it asks for the key and no auto enrol happens. 

How can I achieve this behavior: 
* Auto enrol enabled for a specific course (with only textpage checked, alternatively Link/URL)  
* Auto enrol should happen when entering a link to a textpage / Link/URL within that course
* Users cannot enrol in the couse without knowing that they need to enter a link to an existing textpage / Link/URL

(using Moodle 3.5)

**Comment by VOOM108** [comment]
I had a look at the closed issues and found this: https://github.com/catalyst/moodle-enrol_auto/issues/1

bynare says: "you need to Guest access in your course ;)"

I don't get it.... I want the user to be enrolled, hence "auto enrol" - and I need only authenticated users to be enrolled in the course when viewing an activity within that course. What has guest access got to do with this?

**Comment by danmarsden** [comment]
sounds like what you really want is enrolment on course view - not activity access like you have set.

If you want to use "activity access" as the trigger then your users need another way to access the course that doesn't trigger enrolment... hence why guest access is required for this type of auto-enrolment.

**Comment by VOOM108** [comment]
No, because on course view anyone could enter the course who can find the course.... If that is how activity view works, it makes no sense for us, because with guest view again anyone could enter the course. We need a way to enrol user who know a specific link and only those. Also they should not be prompted to enter a key. 

But I have found a way to achieve what we need by hiding the course via CSS. Now with course auto enrol the users who know the link to the course get enrolled and after that they find the course in their course list to enter it again while it stays hidden to anyone else. 

Of course an enrolment method that would encode the key in a link would be a perfect fit, but that is not on the horizon it seems.

**Comment by danmarsden** [comment]
thanks for the feedback - there may be other ways to achieve what you want using other plugins - you might want to ask in the community forums on moodle.org to see if anyone has any ideas. 

at a technical level - because "require_course_login()" is triggered before the activity view events are triggered unless you're allowing enrolment to occur at course view or allowing guests to access the course - the event "activity viewed" is never triggered and so cannot be picked up by this plugin.

Of course - we're always open to funding for feature development and pull requests are also welcome.

all the best!

**Comment by VOOM108** [comment]
I have been looking for other ways / plugins already and using the auto enrol already was a workaround. But I am quite content with the CSS/auto enrol solution we have now :)
